include: package:lint/analysis_options.yaml

analyzer:
  exclude: [build/**]
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false

linter:
  rules:
  # ------ Disable individual rules ----- #
  #                 ---                   #
  # Turn off what you don't like.         #
  # ------------------------------------- #

  # Make constructors the first thing in every class
  sort_constructors_first: true

  prefer_single_quotes: true

  # Blindly follow the Flutter code style, which prefers types everywhere
  always_specify_types: true
