include: package:lint/analysis_options.yaml

linter:
  rules:
  # ------ Disable individual rules ----- #
  #                 ---                   #
  # Turn off what you don't like.         #
  # ------------------------------------- #
