name: InvenTree
description: InvenTree stock management

# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning

# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.2.6+14

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0

  cupertino_icons: ^1.0.3
  http: ^0.13.0
  cached_network_image: ^3.0.0            # Download and cache remote images
  qr_code_scanner: ^0.5.1                 # Barcode scanning
  package_info: ^2.0.0                    # App information introspection
  device_info: ^2.0.0                     # Information about the device
  font_awesome_flutter: ^9.1.0            # FontAwesome icon set
  flutter_speed_dial: ^3.0.5              # FAB menu elements
  sentry_flutter: 5.0.0                   # Error reporting
  flutter_typeahead: ^3.1.0               # Auto-complete input field
  image_picker: ^0.8.0                    # Select or take photos
  url_launcher: 6.0.0                     # Open link in system browser
  flutter_markdown: ^0.6.2                # Rendering markdown
  camera:                                 # Camera
  path_provider: 2.0.1                    # Local file storage
  sembast: ^3.1.0+2                       # NoSQL data storage
  one_context: ^1.1.0                     # Dialogs without requiring context
  infinite_scroll_pagination: ^3.1.0      # Let the server do all the work!
  audioplayers: ^0.19.0                   # Play audio files
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/image/icon.png
    - assets/release_notes.md
    - assets/credits.md
    - assets/sounds/barcode_scan.mp3
    - assets/sounds/barcode_error.mp3
    - assets/sounds/server_error.mp3

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
