# Run flutter linting checks

name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Setup Flutter 
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.3'
      - name: Collect Translation Files
        run: |
          cd lib/l10n
          python3 collect_translations.py
      - name: Run Unit Tests
        run: |
          cp lib/dummy_dsn.dart lib/dsn.dart
          python3 find_dart_files.py
          flutter pub get
          flutter analyze
          flutter test --coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
